FROM python:3.8-buster

WORKDIR /home/familyVoice

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY app ./app
COPY website ./website
COPY websiteMain.py . 

ENV FLASK_APP websiteMain.py

EXPOSE 8000
ENTRYPOINT ["gunicorn"]
CMD ["-k", "eventlet","-w", "4", "-b", "0.0.0.0:8000", "--log-level", "debug", "websiteMain:app"]
