version: '3'

services:
    website:
        build:
            context: .
            dockerfile: Dockerfile.website
        ports: 
            - "8000:8000"
        environment:
            - MESSAGE_QUEUE_URI=redis://redis:6379
            - DATABASE_URL=mysql+pymysql://familyvoice:vewysecret@database:3306/familyvoice

        links:
            - "redis"
        depends_on:
            - "commserver"  
            - "database"
        restart: always
        
    commserver:
        build:
            context: .
            dockerfile: Dockerfile.commserver
        ports: 
            - "9999:9999"
        environment:
            - MESSAGE_QUEUE_URI=redis://redis:6379
            - PYTHONUNBUFFERED=0
            - DATABASE_URL=mysql+pymysql://familyvoice:vewysecret@database:3306/familyvoice
        links:
            - "redis"
        depends_on:
            - "redis"
            - "database"
        restart: always
        command: --worker-class eventlet -w 1 -b 0.0.0.0:9999 --log-level debug commserver:app 

    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
        restart: always
        
    database:
        image: "mysql/mysql-server:latest"

        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=familyvoice
            - MYSQL_USER=familyvoice
            - MYSQL_PASSWORD=vewysecret
        restart: always

        